
CREATE TABLE TCO_ABCODE
(
  PK                NUMBER(10)                  NOT NULL,
  TCO_ABCODEGRP_PK  NUMBER(10)                  NOT NULL,
  ORD               NUMBER                      NOT NULL,
  CODE              VARCHAR2(10 BYTE)           NOT NULL,
  GRP_CODE          VARCHAR2(8 BYTE),
  DEF_YN            VARCHAR2(1 BYTE),
  CODE_NM           VARCHAR2(100 BYTE),
  CODE_LNM          VARCHAR2(100 BYTE),
  CODE_FNM          VARCHAR2(100 BYTE),
  NUM_VALUE1        NUMBER(10),
  NUM_VALUE2        NUMBER(10),
  NUM_VALUE3        NUMBER(10),
  CHA_VALUE1        VARCHAR2(50 BYTE),
  CHA_VALUE2        VARCHAR2(50 BYTE),
  CHA_VALUE3        VARCHAR2(50 BYTE),
  USE_IF            VARCHAR2(1 BYTE)            DEFAULT 0,
  ST_DATE           VARCHAR2(8 BYTE)            DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'),
  END_DATE          VARCHAR2(8 BYTE),
  DEL_IF            NUMBER(10)                  DEFAULT 0,
  CRT_DT            DATE                        DEFAULT SYSDATE,
  CRT_BY            VARCHAR2(10 BYTE),
  MOD_DT            DATE,
  MOD_BY            VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN TCO_ABCODE.PK IS 'Primary Key';

COMMENT ON COLUMN TCO_ABCODE.TCO_ABCODEGRP_PK IS 'TC_ABCODE_MST Primary Key';

COMMENT ON COLUMN TCO_ABCODE.CODE IS 'Define Basic Code';

COMMENT ON COLUMN TCO_ABCODE.GRP_CODE IS 'GROUP CODE';

COMMENT ON COLUMN TCO_ABCODE.DEF_YN IS 'Y = DEFAULT, N = NORMAL';

COMMENT ON COLUMN TCO_ABCODE.CODE_NM IS 'Define Code NAME';

COMMENT ON COLUMN TCO_ABCODE.CODE_LNM IS 'Define Code LOCAL NAME';

COMMENT ON COLUMN TCO_ABCODE.CODE_FNM IS 'Define Code KOREAN NAME';

COMMENT ON COLUMN TCO_ABCODE.NUM_VALUE1 IS 'Specification Number1 ( How can you using that - Define meaning to same column in Master )';

COMMENT ON COLUMN TCO_ABCODE.NUM_VALUE2 IS 'Specification Number2 ( How can you using that - Define meaning to same column in Master )';

COMMENT ON COLUMN TCO_ABCODE.NUM_VALUE3 IS 'Specification Number3 ( How can you using that - Define meaning to same column in Master )';

COMMENT ON COLUMN TCO_ABCODE.CHA_VALUE1 IS 'Specification Charecter1 ( How can you using that - Define meaning to same column in Master )';

COMMENT ON COLUMN TCO_ABCODE.CHA_VALUE2 IS 'Specification Charecter2 ( How can you using that - Define meaning to same column in Master )';

COMMENT ON COLUMN TCO_ABCODE.CHA_VALUE3 IS 'Specification Charecter3 ( How can you using that - Define meaning to same column in Master )';

COMMENT ON COLUMN TCO_ABCODE.USE_IF IS 'COAB0020:CURRENT USING(0) OR NOT(1)';

COMMENT ON COLUMN TCO_ABCODE.ST_DATE IS 'START DATE';

COMMENT ON COLUMN TCO_ABCODE.END_DATE IS 'END DATE';

COMMENT ON COLUMN TCO_ABCODE.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_ABCODE.CRT_DT IS 'CREAT DATE';

COMMENT ON COLUMN TCO_ABCODE.CRT_BY IS 'CREATOR';

COMMENT ON COLUMN TCO_ABCODE.MOD_DT IS 'MODIFIED DATE';

COMMENT ON COLUMN TCO_ABCODE.MOD_BY IS 'MODIFIER';


CREATE TABLE TCO_ABCODEGRP
(
  PK         NUMBER(10)                         NOT NULL,
  ID         VARCHAR2(8 BYTE)                   NOT NULL,
  P_PK       NUMBER(10),
  CODE_TYPE  VARCHAR2(1 BYTE),
  CODE_LEN   VARCHAR2(1 BYTE),
  SYS_YN     VARCHAR2(1 BYTE),
  DTL_TYPE   VARCHAR2(1 BYTE),
  CODE_GRP   NUMBER(10),
  REM_NUM1   VARCHAR2(100 BYTE),
  REM_NUM2   VARCHAR2(100 BYTE),
  REM_NUM3   VARCHAR2(100 BYTE),
  REM_CHA1   VARCHAR2(100 BYTE),
  REM_CHA2   VARCHAR2(100 BYTE),
  REM_CHA3   VARCHAR2(100 BYTE),
  REMARK     VARCHAR2(100 BYTE),
  USE_IF     VARCHAR2(1 BYTE)                   DEFAULT 0,
  DEL_IF     NUMBER(10)                         DEFAULT 0,
  CRT_DT     DATE                               DEFAULT SYSDATE,
  CRT_BY     VARCHAR2(10 BYTE),
  MOD_DT     DATE,
  MOD_BY     VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN TCO_ABCODEGRP.PK IS 'Primary Key';

COMMENT ON COLUMN TCO_ABCODEGRP.ID IS 'Define of Master Code';

COMMENT ON COLUMN TCO_ABCODEGRP.P_PK IS 'PARENT Primary Key';

COMMENT ON COLUMN TCO_ABCODEGRP.CODE_TYPE IS 'COAB0010:C:CHAR,N:NUMBER';

COMMENT ON COLUMN TCO_ABCODEGRP.CODE_LEN IS 'CODE LENGTH';

COMMENT ON COLUMN TCO_ABCODEGRP.SYS_YN IS 'COAB0030:system Option flag(Y:no Modify,N:Modify)';

COMMENT ON COLUMN TCO_ABCODEGRP.DTL_TYPE IS 'COAB0020:TC_CODE_DTL KIND(SUPER,CODE,SUBCODE)';

COMMENT ON COLUMN TCO_ABCODEGRP.CODE_GRP IS 'IF DTL_KIND=SUBCODE, SET GROUP S PK';

COMMENT ON COLUMN TCO_ABCODEGRP.REM_NUM1 IS 'Define Meaning that TC_code_dtl.num_value1';

COMMENT ON COLUMN TCO_ABCODEGRP.REM_NUM2 IS 'Define Meaning that TC_code_dtl.num_value2';

COMMENT ON COLUMN TCO_ABCODEGRP.REM_NUM3 IS 'Define Meaning that TC_code_dtl.num_value3';

COMMENT ON COLUMN TCO_ABCODEGRP.REM_CHA1 IS 'Define Meaning that TC_code_dtl.cha_value1';

COMMENT ON COLUMN TCO_ABCODEGRP.REM_CHA2 IS 'Define Meaning that TC_code_dtl.cha_value2';

COMMENT ON COLUMN TCO_ABCODEGRP.REM_CHA3 IS 'Define Meaning that TC_code_dtl.cha_value3';

COMMENT ON COLUMN TCO_ABCODEGRP.REMARK IS 'Description';

COMMENT ON COLUMN TCO_ABCODEGRP.USE_IF IS 'COAB0040:CURRENT USING(0) OR NOT(1)';

COMMENT ON COLUMN TCO_ABCODEGRP.DEL_IF IS 'COAB0050:DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_ABCODEGRP.CRT_DT IS 'CREAT DATE';

COMMENT ON COLUMN TCO_ABCODEGRP.CRT_BY IS 'CREATOR';

COMMENT ON COLUMN TCO_ABCODEGRP.MOD_DT IS 'MODIFIED DATE';

COMMENT ON COLUMN TCO_ABCODEGRP.MOD_BY IS 'MODIFIER';


CREATE TABLE TCO_ABCODEGRP_TMP
(
  PK         NUMBER(10)                         NOT NULL,
  ID         VARCHAR2(8 BYTE)                   NOT NULL,
  P_PK       NUMBER(10),
  CODE_TYPE  VARCHAR2(1 BYTE),
  CODE_LEN   VARCHAR2(1 BYTE),
  SYS_YN     VARCHAR2(1 BYTE),
  DTL_TYPE   VARCHAR2(1 BYTE),
  CODE_GRP   NUMBER(10),
  REM_NUM1   VARCHAR2(100 BYTE),
  REM_NUM2   VARCHAR2(100 BYTE),
  REM_NUM3   VARCHAR2(100 BYTE),
  REM_CHA1   VARCHAR2(100 BYTE),
  REM_CHA2   VARCHAR2(100 BYTE),
  REM_CHA3   VARCHAR2(100 BYTE),
  REMARK     VARCHAR2(100 BYTE),
  USE_IF     VARCHAR2(1 BYTE),
  DEL_IF     NUMBER(10),
  CRT_DT     DATE,
  CRT_BY     VARCHAR2(10 BYTE),
  MOD_DT     DATE,
  MOD_BY     VARCHAR2(10 BYTE)
)
NOLOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE TCO_ABCODESQL
(
  PK                NUMBER(10)                  NOT NULL,
  TCO_ABCODEGRP_PK  NUMBER(10)                  NOT NULL,
  SQL_CASE          VARCHAR2(2 BYTE)            DEFAULT 0,
  REMARK            VARCHAR2(200 BYTE),
  SQL_TEXT          VARCHAR2(4000 BYTE),
  USE_IF            VARCHAR2(1 BYTE)            DEFAULT 0,
  DEL_IF            NUMBER(10)                  DEFAULT 0,
  CRT_DT            DATE                        DEFAULT SYSDATE,
  CRT_BY            VARCHAR2(10 BYTE),
  MOD_DT            DATE,
  MOD_BY            VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN TCO_ABCODESQL.PK IS 'Primary Key';

COMMENT ON COLUMN TCO_ABCODESQL.TCO_ABCODEGRP_PK IS 'TCO_ABCODEGRP_MST pk';

COMMENT ON COLUMN TCO_ABCODESQL.SQL_CASE IS 'SQL CASE(BY DEVELOPER)';

COMMENT ON COLUMN TCO_ABCODESQL.REMARK IS 'DESCRIPTION FOR SQL';

COMMENT ON COLUMN TCO_ABCODESQL.SQL_TEXT IS 'REAL SQL';

COMMENT ON COLUMN TCO_ABCODESQL.USE_IF IS 'COAB0040:CURRENT USING(0) OR NOT(1)';

COMMENT ON COLUMN TCO_ABCODESQL.DEL_IF IS 'COAB0050:DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_ABCODESQL.CRT_DT IS 'CREAT DATE';

COMMENT ON COLUMN TCO_ABCODESQL.CRT_BY IS 'CREATOR';

COMMENT ON COLUMN TCO_ABCODESQL.MOD_DT IS 'MODIFIED DATE';

COMMENT ON COLUMN TCO_ABCODESQL.MOD_BY IS 'MODIFIER';


CREATE TABLE TCO_ABCODESQLPARM
(
  PK                NUMBER(10)                  NOT NULL,
  TCO_ABCODESQL_PK  NUMBER(10),
  PARM_ORD          NUMBER(2),
  PARM_NM           VARCHAR2(20 BYTE),
  PARM_IO           VARCHAR2(5 BYTE),
  PARM_TYPE         VARCHAR2(5 BYTE),
  REMARK            VARCHAR2(200 BYTE),
  USE_IF            VARCHAR2(1 BYTE)            DEFAULT 0,
  DEL_IF            NUMBER(10)                  DEFAULT 0,
  CRT_DT            DATE                        DEFAULT SYSDATE,
  CRT_BY            VARCHAR2(10 BYTE),
  MOD_DT            DATE,
  MOD_BY            VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON COLUMN TCO_ABCODESQLPARM.TCO_ABCODESQL_PK IS 'TC_ABCODE_MST pk';

COMMENT ON COLUMN TCO_ABCODESQLPARM.PARM_ORD IS 'PARAMETER ORDER';

COMMENT ON COLUMN TCO_ABCODESQLPARM.PARM_NM IS 'PARAMETER NAME';

COMMENT ON COLUMN TCO_ABCODESQLPARM.PARM_IO IS 'IN/OUT COAB0100';

COMMENT ON COLUMN TCO_ABCODESQLPARM.PARM_TYPE IS 'DATA TYPE COAB0090';

COMMENT ON COLUMN TCO_ABCODESQLPARM.REMARK IS 'DESCRIPTION FOR PARAMETER';

COMMENT ON COLUMN TCO_ABCODESQLPARM.USE_IF IS 'COAB0040:CURRENT USING(0) OR NOT(1)';

COMMENT ON COLUMN TCO_ABCODESQLPARM.DEL_IF IS 'COAB0050:DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_ABCODESQLPARM.CRT_DT IS 'CREAT DATE';

COMMENT ON COLUMN TCO_ABCODESQLPARM.CRT_BY IS 'CREATOR';

COMMENT ON COLUMN TCO_ABCODESQLPARM.MOD_DT IS 'MODIFIED DATE';

COMMENT ON COLUMN TCO_ABCODESQLPARM.MOD_BY IS 'MODIFIER';

COMMENT ON COLUMN TCO_ABCODESQLPARM.PK IS 'Primary Key';


CREATE TABLE TCO_ABCODESQL_TMP
(
  PK                NUMBER(10)                  NOT NULL,
  TCO_ABCODEGRP_PK  NUMBER(10)                  NOT NULL,
  SQL_CASE          VARCHAR2(2 BYTE),
  REMARK            VARCHAR2(200 BYTE),
  SQL_TEXT          VARCHAR2(4000 BYTE),
  USE_IF            VARCHAR2(1 BYTE),
  DEL_IF            NUMBER(10),
  CRT_DT            DATE,
  CRT_BY            VARCHAR2(10 BYTE),
  MOD_DT            DATE,
  MOD_BY            VARCHAR2(10 BYTE)
)
NOLOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODE ON TCO_ABCODE
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODE_IDX01 ON TCO_ABCODE
(TCO_ABCODEGRP_PK, CODE, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODEGRP ON TCO_ABCODEGRP
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODEGRP_IDX01 ON TCO_ABCODEGRP
(ID, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODESQL ON TCO_ABCODESQL
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODESQL_IDX01 ON TCO_ABCODESQL
(TCO_ABCODEGRP_PK, SQL_CASE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODESQLPARM ON TCO_ABCODESQLPARM
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_ABCODESQLPARM_IDX01 ON TCO_ABCODESQLPARM
(TCO_ABCODESQL_PK, PARM_ORD, DEL_IF)
LOGGING
NOPARALLEL;


CREATE OR REPLACE TRIGGER TRGCO_ABCODEGRP
	BEFORE
	UPDATE OF DEL_IF ON TCO_ABCODEGRP
	FOR EACH ROW
WHEN (
new.DEL_if <> 0
      )
DECLARE
        CNT		number;
        CD       varchar2(10);
        err_num NUMBER;
        err_msg VARCHAR2(100);
	BEGIN
		SELECT COUNT(*), MIN(CODE)
			INTO CNT , CD
			FROM TCO_ABCODE
			WHERE TCO_ABCODEGRP_PK = :old.pk
			AND   DEL_IF = 0;
		IF(CNT>0) THEN raise_application_error( -20601, 'CHECK ' || :OLD.ID || ' HAS AVAILABLE CODE AS '|| CD  );
		END IF;
	EXCEPTION
		WHEN OTHERS THEN
             err_num := SQLCODE;
             err_msg := SUBSTRB(SQLERRM, 1, 100);
			 raise_application_error( err_num, 'TRGCO_ABCODEGRP ' || err_msg  );
    END;
/
SHOW ERRORS;



CREATE PUBLIC SYNONYM TCO_ABCODESQL FOR TCO_ABCODESQL;


CREATE PUBLIC SYNONYM TCO_ABCODEGRP FOR TCO_ABCODEGRP;


CREATE PUBLIC SYNONYM TCO_ABCODE FOR TCO_ABCODE;


CREATE PUBLIC SYNONYM TCO_ABCODESQLPARM FOR TCO_ABCODESQLPARM;


CREATE PUBLIC SYNONYM TCO_ABCODEGRP_TMP FOR TCO_ABCODEGRP_TMP;


CREATE PUBLIC SYNONYM TCO_ABCODESQL_TMP FOR TCO_ABCODESQL_TMP;


ALTER TABLE TCO_ABCODE ADD (
  CONSTRAINT TCO_ABCODE PRIMARY KEY (PK));


ALTER TABLE TCO_ABCODEGRP ADD (
  CONSTRAINT TCO_ABCODEGRP PRIMARY KEY (PK));


ALTER TABLE TCO_ABCODESQL ADD (
  CONSTRAINT TCO_ABCODESQL PRIMARY KEY (PK));


ALTER TABLE TCO_ABCODESQLPARM ADD (
  CONSTRAINT TCO_ABCODESQLPARM PRIMARY KEY (PK));


GRANT SELECT ON  TCO_ABCODESQL_TMP TO PUBLIC;

GRANT SELECT ON  TCO_ABCODESQLPARM TO PUBLIC;

GRANT SELECT ON  TCO_ABCODESQL TO PUBLIC;

GRANT SELECT ON  TCO_ABCODEGRP_TMP TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  TCO_ABCODEGRP TO PUBLIC;

GRANT SELECT ON  TCO_ABCODE TO PUBLIC;


