
CREATE TABLE TCO_EOBIZORG
(
  PK                 NUMBER(10)                 NOT NULL,
  TCO_EOBIZPLACE_PK  NUMBER(10)                 NOT NULL,
  BIZORG_NAME        VARCHAR2(40 BYTE)          NOT NULL,
  TCO_EODEPT_PK      NUMBER(10),
  SALEORG_YN         VARCHAR2(1 BYTE),
  PURORG_YN          VARCHAR2(1 BYTE),
  REMARK             VARCHAR2(50 BYTE),
  USE_YN             VARCHAR2(1 BYTE)           DEFAULT 'Y',
  ST_DATE            VARCHAR2(8 BYTE)           DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'),
  END_DATE           VARCHAR2(8 BYTE),
  DEL_IF             NUMBER(10)                 DEFAULT 0,
  CRT_DT             DATE                       DEFAULT SYSDATE,
  CRT_BY             VARCHAR2(10 BYTE),
  MOD_DT             DATE,
  MOD_BY             VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EOBIZORG IS 'BIZ PLACE ORGANIZATION';

COMMENT ON COLUMN TCO_EOBIZORG.PK IS 'Primary Key';

COMMENT ON COLUMN TCO_EOBIZORG.TCO_EOBIZPLACE_PK IS 'BIZPLACE PK';

COMMENT ON COLUMN TCO_EOBIZORG.BIZORG_NAME IS 'BIZ ORG NAME';

COMMENT ON COLUMN TCO_EOBIZORG.TCO_EODEPT_PK IS 'HR DEPARTMENT PK';

COMMENT ON COLUMN TCO_EOBIZORG.SALEORG_YN IS 'SALE ORG Y N';

COMMENT ON COLUMN TCO_EOBIZORG.PURORG_YN IS 'PURCHASING ORG Y N';

COMMENT ON COLUMN TCO_EOBIZORG.REMARK IS 'REMARK';

COMMENT ON COLUMN TCO_EOBIZORG.USE_YN IS 'COAB0040:CURRENT USING(Y) OR NOT(N)';

COMMENT ON COLUMN TCO_EOBIZORG.ST_DATE IS 'START DATE';

COMMENT ON COLUMN TCO_EOBIZORG.END_DATE IS 'END DATE';

COMMENT ON COLUMN TCO_EOBIZORG.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EOBIZORG.CRT_DT IS 'CREATOR';

COMMENT ON COLUMN TCO_EOBIZORG.CRT_BY IS 'CREAT DATE';

COMMENT ON COLUMN TCO_EOBIZORG.MOD_DT IS 'MODIFIER';

COMMENT ON COLUMN TCO_EOBIZORG.MOD_BY IS 'MODIFIED DATE';


CREATE TABLE TCO_EOBIZPLACE
(
  PK                NUMBER(10)                  NOT NULL,
  TCO_EOCOMPANY_PK  NUMBER(10)                  NOT NULL,
  TCO_DCCUST_PK     NUMBER(10),
  LOC_ID            VARCHAR2(10 BYTE)           NOT NULL,
  LOC_NM            VARCHAR2(40 BYTE),
  LOC_LNM           VARCHAR2(40 BYTE),
  LOC_FNM           VARCHAR2(40 BYTE),
  NATION            VARCHAR2(10 BYTE),
  REG_NO            VARCHAR2(13 BYTE),
  TAX_CD            VARCHAR2(30 BYTE),
  TAX_OFFICE        VARCHAR2(10 BYTE),
  REPRESENTATIVE    VARCHAR2(40 BYTE),
  ZIP_CODE          VARCHAR2(10 BYTE),
  ADDR_NM1          VARCHAR2(200 BYTE),
  ADDR_LNM1         VARCHAR2(200 BYTE),
  ADDR_NM2          VARCHAR2(200 BYTE),
  ADDR_LNM2         VARCHAR2(200 BYTE),
  ADDR_NM3          VARCHAR2(200 BYTE),
  ADDR_LNM3         VARCHAR2(200 BYTE),
  PHONE_NO          VARCHAR2(100 BYTE),
  FAX_NO            VARCHAR2(100 BYTE),
  BIZ_TYPE          VARCHAR2(10 BYTE),
  BIZ_ITEM          VARCHAR2(200 BYTE),
  BIZ_GRP           VARCHAR2(200 BYTE),
  REMARK            VARCHAR2(200 BYTE),
  USE_YN            VARCHAR2(1 BYTE)            DEFAULT 'Y',
  ST_DATE           VARCHAR2(8 BYTE)            DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'),
  END_DATE          VARCHAR2(8 BYTE),
  DEL_IF            NUMBER(10)                  DEFAULT 0,
  CRT_DT            DATE                        DEFAULT SYSDATE,
  CRT_BY            VARCHAR2(10 BYTE),
  MOD_DT            DATE,
  MOD_BY            VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EOBIZPLACE IS 'BISINESS LOCATION';

COMMENT ON COLUMN TCO_EOBIZPLACE.PK IS 'Primary Key';

COMMENT ON COLUMN TCO_EOBIZPLACE.TCO_EOCOMPANY_PK IS 'COMPANY CODE';

COMMENT ON COLUMN TCO_EOBIZPLACE.TCO_DCCUST_PK IS 'CUSTOMER=RELATED COMPANY PK';

COMMENT ON COLUMN TCO_EOBIZPLACE.LOC_ID IS 'BIZ PLACE ID';

COMMENT ON COLUMN TCO_EOBIZPLACE.LOC_NM IS 'BIZ PLACE  NAME';

COMMENT ON COLUMN TCO_EOBIZPLACE.LOC_LNM IS 'LOCAL NAME';

COMMENT ON COLUMN TCO_EOBIZPLACE.LOC_FNM IS 'FOREIGN NAME';

COMMENT ON COLUMN TCO_EOBIZPLACE.NATION IS 'COAB080:NATION';

COMMENT ON COLUMN TCO_EOBIZPLACE.REG_NO IS 'REGISTER NO';

COMMENT ON COLUMN TCO_EOBIZPLACE.TAX_CD IS 'TAX CODE';

COMMENT ON COLUMN TCO_EOBIZPLACE.TAX_OFFICE IS 'COEO0050:TAX OFFICE';

COMMENT ON COLUMN TCO_EOBIZPLACE.REPRESENTATIVE IS 'REPRESENTATIVE NAME';

COMMENT ON COLUMN TCO_EOBIZPLACE.ZIP_CODE IS 'ZIP CODE';

COMMENT ON COLUMN TCO_EOBIZPLACE.ADDR_NM1 IS 'ENGLISH ADDRESS FOR 1ST LINE';

COMMENT ON COLUMN TCO_EOBIZPLACE.ADDR_LNM1 IS 'LOCAL ADDRESS FOR 1ST LINE';

COMMENT ON COLUMN TCO_EOBIZPLACE.ADDR_NM2 IS 'ENGLISH ADDRESS FOR 2ND LINE';

COMMENT ON COLUMN TCO_EOBIZPLACE.ADDR_LNM2 IS 'LOCAL ADDRESS FOR 2ND LINE';

COMMENT ON COLUMN TCO_EOBIZPLACE.ADDR_NM3 IS 'ENGLISH ADDRESS FOR 3RD LINE';

COMMENT ON COLUMN TCO_EOBIZPLACE.ADDR_LNM3 IS 'LOCAL ADDRESS FOR 3RD LINE';

COMMENT ON COLUMN TCO_EOBIZPLACE.PHONE_NO IS 'PHONE NO';

COMMENT ON COLUMN TCO_EOBIZPLACE.FAX_NO IS 'FAX NO';

COMMENT ON COLUMN TCO_EOBIZPLACE.BIZ_TYPE IS 'CODC0030:0(CORPORATION)1(PRIVATE)..';

COMMENT ON COLUMN TCO_EOBIZPLACE.BIZ_ITEM IS 'MAIN ITEM';

COMMENT ON COLUMN TCO_EOBIZPLACE.BIZ_GRP IS 'MARKET GROUP';

COMMENT ON COLUMN TCO_EOBIZPLACE.REMARK IS 'REMARK';

COMMENT ON COLUMN TCO_EOBIZPLACE.USE_YN IS 'COAB0040:CURRENT USING(0) OR NOT(1)';

COMMENT ON COLUMN TCO_EOBIZPLACE.ST_DATE IS 'START DATE';

COMMENT ON COLUMN TCO_EOBIZPLACE.END_DATE IS 'END DATE';

COMMENT ON COLUMN TCO_EOBIZPLACE.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EOBIZPLACE.CRT_DT IS 'CREATOR';

COMMENT ON COLUMN TCO_EOBIZPLACE.CRT_BY IS 'CREAT DATE';

COMMENT ON COLUMN TCO_EOBIZPLACE.MOD_DT IS 'MODIFIER';

COMMENT ON COLUMN TCO_EOBIZPLACE.MOD_BY IS 'MODIFIED DATE';


CREATE TABLE TCO_EOCOMPANY
(
  PK           NUMBER(10)                       NOT NULL,
  COM_ID       VARCHAR2(2 BYTE)                 NOT NULL,
  COM_NM       VARCHAR2(40 BYTE)                NOT NULL,
  NATION       VARCHAR2(10 BYTE),
  LOC_NATION   VARCHAR2(10 BYTE),
  FOR_NATION   VARCHAR2(10 BYTE),
  COM_LNM      VARCHAR2(40 BYTE),
  COM_FNM      VARCHAR2(40 BYTE),
  P_PK         NUMBER(10),
  COM_GRP      VARCHAR2(2 BYTE),
  ACNT_MMDATE  VARCHAR2(8 BYTE),
  AC_GRP       VARCHAR2(10 BYTE),
  CORP_NO      VARCHAR2(15 BYTE),
  PRSN_NAME    VARCHAR2(20 BYTE),
  RES_NO       VARCHAR2(14 BYTE),
  BIZ_TYPE     VARCHAR2(10 BYTE),
  BIZ_ITEM     VARCHAR2(200 BYTE),
  BIZ_GRP      VARCHAR2(200 BYTE),
  ZIP_CODE     VARCHAR2(10 BYTE),
  ADDR_NM1     VARCHAR2(200 BYTE),
  ADDR_LNM1    VARCHAR2(200 BYTE),
  ADDR_NM2     VARCHAR2(200 BYTE),
  ADDR_LNM2    VARCHAR2(200 BYTE),
  ADDR_NM3     VARCHAR2(200 BYTE),
  ADDR_LNM3    VARCHAR2(200 BYTE),
  PHONE_NO     VARCHAR2(100 BYTE),
  FAX_NO       VARCHAR2(100 BYTE),
  URL_ADDR     VARCHAR2(100 BYTE),
  USE_YN       VARCHAR2(1 BYTE)                 DEFAULT 'Y',
  ST_DATE      VARCHAR2(8 BYTE)                 DEFAULT TO_CHAR(SYSDATE,'YYYYMMDD'),
  END_DATE     VARCHAR2(8 BYTE),
  DEL_IF       NUMBER(10)                       DEFAULT 0,
  CRT_DT       DATE                             DEFAULT SYSDATE,
  CRT_BY       VARCHAR2(10 BYTE),
  MOD_DT       DATE,
  MOD_BY       VARCHAR2(10 BYTE),
  SERIAL_NO    VARCHAR2(100 BYTE),
  TAX_CODE     VARCHAR2(100 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EOCOMPANY IS 'COMPANY MASTER';

COMMENT ON COLUMN TCO_EOCOMPANY.PK IS 'Primary Key';

COMMENT ON COLUMN TCO_EOCOMPANY.COM_ID IS 'COMPANY ID';

COMMENT ON COLUMN TCO_EOCOMPANY.COM_NM IS 'COMPANY NAME';

COMMENT ON COLUMN TCO_EOCOMPANY.NATION IS 'COAB0080:NATION';

COMMENT ON COLUMN TCO_EOCOMPANY.LOC_NATION IS 'COAB0080:NATION OF LOCAL NAME';

COMMENT ON COLUMN TCO_EOCOMPANY.FOR_NATION IS 'COAB0080:NATION OF FOREIGN NAME';

COMMENT ON COLUMN TCO_EOCOMPANY.COM_LNM IS 'LOCAL NAME';

COMMENT ON COLUMN TCO_EOCOMPANY.COM_FNM IS 'FOREIGN NAME';

COMMENT ON COLUMN TCO_EOCOMPANY.P_PK IS 'PARENT COMPANY';

COMMENT ON COLUMN TCO_EOCOMPANY.COM_GRP IS 'COEO0010:COMPANY GROUP';

COMMENT ON COLUMN TCO_EOCOMPANY.ACNT_MMDATE IS 'ACCOUNT MONTHLY CLOSING DATE';

COMMENT ON COLUMN TCO_EOCOMPANY.AC_GRP IS 'Account Group=ACAB0010';

COMMENT ON COLUMN TCO_EOCOMPANY.CORP_NO IS 'CORPORATION NO';

COMMENT ON COLUMN TCO_EOCOMPANY.PRSN_NAME IS 'PRESIDEDENT NAME';

COMMENT ON COLUMN TCO_EOCOMPANY.RES_NO IS 'PRESIDEDENT NO';

COMMENT ON COLUMN TCO_EOCOMPANY.BIZ_TYPE IS 'CODC0030:0(CORPORATION)1(PRIVATE)..';

COMMENT ON COLUMN TCO_EOCOMPANY.BIZ_ITEM IS 'MAIN ITEM';

COMMENT ON COLUMN TCO_EOCOMPANY.BIZ_GRP IS 'MARKET GROUP';

COMMENT ON COLUMN TCO_EOCOMPANY.ZIP_CODE IS 'ZIP CODE';

COMMENT ON COLUMN TCO_EOCOMPANY.ADDR_NM1 IS 'ENGLISH ADDRESS FOR 1ST LINE';

COMMENT ON COLUMN TCO_EOCOMPANY.ADDR_LNM1 IS 'LOCAL ADDRESS FOR 1ST LINE';

COMMENT ON COLUMN TCO_EOCOMPANY.ADDR_NM2 IS 'ENGLISH ADDRESS FOR 2ND LINE';

COMMENT ON COLUMN TCO_EOCOMPANY.ADDR_LNM2 IS 'LOCAL ADDRESS FOR 2ND LINE';

COMMENT ON COLUMN TCO_EOCOMPANY.ADDR_NM3 IS 'ENGLISH ADDRESS FOR 3RD LINE';

COMMENT ON COLUMN TCO_EOCOMPANY.ADDR_LNM3 IS 'LOCAL ADDRESS FOR 3RD LINE';

COMMENT ON COLUMN TCO_EOCOMPANY.PHONE_NO IS 'PHONE NO';

COMMENT ON COLUMN TCO_EOCOMPANY.FAX_NO IS 'FAX NO';

COMMENT ON COLUMN TCO_EOCOMPANY.URL_ADDR IS 'URL ADDRESS';

COMMENT ON COLUMN TCO_EOCOMPANY.USE_YN IS 'COAB0040:CURRENT USING(Y) OR NOT(N)';

COMMENT ON COLUMN TCO_EOCOMPANY.ST_DATE IS 'START DATE';

COMMENT ON COLUMN TCO_EOCOMPANY.END_DATE IS 'END DATE';

COMMENT ON COLUMN TCO_EOCOMPANY.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EOCOMPANY.CRT_DT IS 'CREATOR';

COMMENT ON COLUMN TCO_EOCOMPANY.CRT_BY IS 'CREAT DATE';

COMMENT ON COLUMN TCO_EOCOMPANY.MOD_DT IS 'MODIFIER';

COMMENT ON COLUMN TCO_EOCOMPANY.MOD_BY IS 'MODIFIED DATE';


CREATE TABLE TCO_EODEPT
(
  PK                 NUMBER(10)                 NOT NULL,
  DEPT_ID            VARCHAR2(10 BYTE)          NOT NULL,
  DEPT_TYPE          VARCHAR2(10 BYTE)          NOT NULL,
  DEPT_NM            VARCHAR2(100 BYTE)         NOT NULL,
  DEPT_LNM           VARCHAR2(100 BYTE),
  DEPT_FNM           VARCHAR2(100 BYTE),
  P_PK               NUMBER(10),
  TCO_EOBIZPLACE_PK  NUMBER(10),
  TCO_EOCOMPANY_PK   NUMBER(10),
  TAC_ABBUDGET_PK    NUMBER(10),
  ST_DATE            VARCHAR2(8 BYTE)           NOT NULL,
  END_DATE           VARCHAR2(8 BYTE),
  REMARK             VARCHAR2(100 BYTE),
  DEL_IF             NUMBER(10)                 DEFAULT 0,
  CRT_BY             VARCHAR2(10 BYTE),
  CRT_DT             DATE                       DEFAULT SYSDATE,
  MOD_BY             VARCHAR2(10 BYTE),
  MOD_DT             DATE,
  PLACE_CODE         VARCHAR2(10 BYTE),
  STT                VARCHAR2(10 BYTE)
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EODEPT IS 'DEPARTMENT MASTER';

COMMENT ON COLUMN TCO_EODEPT.TCO_EOBIZPLACE_PK IS 'BIZ PLACE PK';

COMMENT ON COLUMN TCO_EODEPT.TCO_EOCOMPANY_PK IS 'COMPANY PK';

COMMENT ON COLUMN TCO_EODEPT.TAC_ABBUDGET_PK IS 'BUDGET DEPT PK';

COMMENT ON COLUMN TCO_EODEPT.ST_DATE IS 'VALID FROM DATE';

COMMENT ON COLUMN TCO_EODEPT.END_DATE IS 'VALID TO DATE';

COMMENT ON COLUMN TCO_EODEPT.REMARK IS 'REMARK';

COMMENT ON COLUMN TCO_EODEPT.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EODEPT.CRT_BY IS 'Create Date';

COMMENT ON COLUMN TCO_EODEPT.CRT_DT IS 'Create By';

COMMENT ON COLUMN TCO_EODEPT.MOD_BY IS 'Modify Date';

COMMENT ON COLUMN TCO_EODEPT.MOD_DT IS 'Modify By';

COMMENT ON COLUMN TCO_EODEPT.PLACE_CODE IS 'PLACE CODE';

COMMENT ON COLUMN TCO_EODEPT.PK IS 'PK';

COMMENT ON COLUMN TCO_EODEPT.DEPT_ID IS 'DEPARTMENT ID';

COMMENT ON COLUMN TCO_EODEPT.DEPT_TYPE IS 'COEO0030:DEPARTMENT TYPE';

COMMENT ON COLUMN TCO_EODEPT.DEPT_NM IS 'DEPARTMENT NAME';

COMMENT ON COLUMN TCO_EODEPT.DEPT_LNM IS 'DEPT LOCAL NAME';

COMMENT ON COLUMN TCO_EODEPT.DEPT_FNM IS 'DEPT FOREIGN NAME';

COMMENT ON COLUMN TCO_EODEPT.P_PK IS 'PARENT PK';


CREATE TABLE TCO_EODEPTAPPOINT
(
  PK                NUMBER(10)                  NOT NULL,
  APPOINT_TITLE     VARCHAR2(100 BYTE)          NOT NULL,
  APPOINT_DATE      VARCHAR2(8 BYTE)            NOT NULL,
  LASTAPPOINT_DATE  VARCHAR2(8 BYTE),
  THR_ABEMP_PK      NUMBER(10)                  NOT NULL,
  CONFIRM_DATE      VARCHAR2(8 BYTE),
  REMARK            VARCHAR2(100 BYTE),
  DEL_IF            NUMBER(10)                  DEFAULT 0,
  CRT_BY            VARCHAR2(10 BYTE),
  CRT_DT            DATE                        DEFAULT SYSDATE,
  MOD_BY            VARCHAR2(10 BYTE),
  MOD_DT            DATE
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EODEPTAPPOINT IS 'DEPARTMENT MASTER';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.PK IS 'PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.APPOINT_TITLE IS 'USER DEFINED TITLE';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.APPOINT_DATE IS 'APPOINMENT DATE';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.LASTAPPOINT_DATE IS 'LAST APPOINMENT DATE';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.THR_ABEMP_PK IS 'EMPLOYEE PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.CONFIRM_DATE IS 'CONFIRM DATE';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.REMARK IS 'REMARK';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.CRT_BY IS 'Create Date';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.CRT_DT IS 'Create By';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.MOD_BY IS 'Modify Date';

COMMENT ON COLUMN TCO_EODEPTAPPOINT.MOD_DT IS 'Modify By';


CREATE TABLE TCO_EODEPTAPPOINTD
(
  PK                    NUMBER(10)              NOT NULL,
  TCO_EODEPTAPPOINT_PK  NUMBER(10)              NOT NULL,
  APPOINT_TYPE          VARCHAR2(10 BYTE)       NOT NULL,
  TCO_EODEPT_PK         NUMBER(10),
  DEPT_TYPE             VARCHAR2(10 BYTE),
  DEPT_ID               VARCHAR2(10 BYTE)       NOT NULL,
  DEPT_NM               VARCHAR2(100 BYTE),
  DEPT_LNM              VARCHAR2(100 BYTE),
  DEPT_FNM              VARCHAR2(100 BYTE),
  P_PK                  NUMBER(10),
  TCO_EOBIZPLACE_PK     NUMBER(10),
  TCO_EOCOMPANY_PK      NUMBER(10),
  TAC_ABBUDGET_PK       NUMBER(10),
  THR_ABEMP_PK          NUMBER(10),
  REMARK                VARCHAR2(100 BYTE),
  DEL_IF                NUMBER(10)              DEFAULT 0,
  CRT_BY                VARCHAR2(10 BYTE),
  CRT_DT                DATE                    DEFAULT SYSDATE,
  MOD_BY                VARCHAR2(10 BYTE),
  MOD_DT                DATE
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EODEPTAPPOINTD IS 'DEPARTMENT MASTER';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.PK IS 'PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.TCO_EODEPTAPPOINT_PK IS 'APPOINMENT MASTER PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.APPOINT_TYPE IS 'COEO0040:APPOINMENT TYPE';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.TCO_EODEPT_PK IS 'DEPARTMENT PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.DEPT_TYPE IS 'COEO0030:DEPARTMENT TYPE';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.DEPT_ID IS 'DEPARTMENT ID';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.DEPT_NM IS 'DEPARTMENT NAME';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.DEPT_LNM IS 'DEPT LOCAL NAME';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.DEPT_FNM IS 'DEPT FOREIGN NAME';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.P_PK IS 'PARENT PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.TCO_EOBIZPLACE_PK IS 'BIZ PLACE PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.TCO_EOCOMPANY_PK IS 'COMPANY PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.TAC_ABBUDGET_PK IS 'BUDGET DEPT PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.THR_ABEMP_PK IS 'DEPARTMENT MANAGER PK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.REMARK IS 'REMARK';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.CRT_BY IS 'Create Date';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.CRT_DT IS 'Create By';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.MOD_BY IS 'Modify Date';

COMMENT ON COLUMN TCO_EODEPTAPPOINTD.MOD_DT IS 'Modify By';


CREATE TABLE TCO_EODEPTHIS
(
  PK                   NUMBER(10)               NOT NULL,
  TCO_EODEPAPPOINT_PK  NUMBER(10)               NOT NULL,
  TCO_EODEPT_PK        NUMBER(10)               NOT NULL,
  DEPT_TYPE            VARCHAR2(10 BYTE),
  DEPT_ID              VARCHAR2(10 BYTE),
  DEPT_NM              VARCHAR2(100 BYTE),
  DEPT_LNM             VARCHAR2(100 BYTE),
  DEPT_FNM             VARCHAR2(100 BYTE),
  P_PK                 NUMBER(10),
  TCO_EOBIZPLACE_PK    NUMBER(10),
  TCO_EOCOMPANY_PK     NUMBER(10),
  TAC_ABBUDGET_PK      NUMBER(10),
  ST_DATE              VARCHAR2(8 BYTE),
  END_DATE             VARCHAR2(8 BYTE),
  REMARK               VARCHAR2(100 BYTE),
  DEL_IF               NUMBER(10)               DEFAULT 0,
  CRT_BY               VARCHAR2(10 BYTE),
  CRT_DT               DATE                     DEFAULT SYSDATE,
  MOD_BY               VARCHAR2(10 BYTE),
  MOD_DT               DATE
)
LOGGING 
NOCACHE
NOPARALLEL;

COMMENT ON TABLE TCO_EODEPTHIS IS 'DEPARTMENT MASTER';

COMMENT ON COLUMN TCO_EODEPTHIS.PK IS 'PK';

COMMENT ON COLUMN TCO_EODEPTHIS.TCO_EODEPAPPOINT_PK IS 'APPOINMENT PK';

COMMENT ON COLUMN TCO_EODEPTHIS.TCO_EODEPT_PK IS 'DEPARTMENT PK';

COMMENT ON COLUMN TCO_EODEPTHIS.DEPT_TYPE IS 'COEO0030:DEPARTMENT TYPE';

COMMENT ON COLUMN TCO_EODEPTHIS.DEPT_ID IS 'DEPARTMENT ID';

COMMENT ON COLUMN TCO_EODEPTHIS.DEPT_NM IS 'DEPARTMENT NAME';

COMMENT ON COLUMN TCO_EODEPTHIS.DEPT_LNM IS 'DEPT LOCAL NAME';

COMMENT ON COLUMN TCO_EODEPTHIS.DEPT_FNM IS 'DEPT FOREIGN NAME';

COMMENT ON COLUMN TCO_EODEPTHIS.P_PK IS 'PARENT PK';

COMMENT ON COLUMN TCO_EODEPTHIS.TCO_EOBIZPLACE_PK IS 'BIZ PLACE PK';

COMMENT ON COLUMN TCO_EODEPTHIS.TCO_EOCOMPANY_PK IS 'COMPANY PK';

COMMENT ON COLUMN TCO_EODEPTHIS.TAC_ABBUDGET_PK IS 'BUDGET DEPT PK';

COMMENT ON COLUMN TCO_EODEPTHIS.ST_DATE IS 'VALID FROM DATE';

COMMENT ON COLUMN TCO_EODEPTHIS.END_DATE IS 'VALID TO DATE';

COMMENT ON COLUMN TCO_EODEPTHIS.REMARK IS 'REMARK';

COMMENT ON COLUMN TCO_EODEPTHIS.DEL_IF IS 'DELETE IF (USE:0, DELETE:PK)';

COMMENT ON COLUMN TCO_EODEPTHIS.CRT_BY IS 'Create Date';

COMMENT ON COLUMN TCO_EODEPTHIS.CRT_DT IS 'Create By';

COMMENT ON COLUMN TCO_EODEPTHIS.MOD_BY IS 'Modify Date';

COMMENT ON COLUMN TCO_EODEPTHIS.MOD_DT IS 'Modify By';


CREATE TABLE TCO_EODEPT_TMP
(
  PK                 NUMBER(10)                 NOT NULL,
  DEPT_ID            VARCHAR2(10 BYTE)          NOT NULL,
  DEPT_TYPE          VARCHAR2(10 BYTE)          NOT NULL,
  DEPT_NM            VARCHAR2(100 BYTE)         NOT NULL,
  DEPT_LNM           VARCHAR2(100 BYTE),
  DEPT_FNM           VARCHAR2(100 BYTE),
  P_PK               NUMBER(10),
  TCO_EOBIZPLACE_PK  NUMBER(10),
  TCO_EOCOMPANY_PK   NUMBER(10),
  TAC_ABBUDGET_PK    NUMBER(10),
  ST_DATE            VARCHAR2(8 BYTE)           NOT NULL,
  END_DATE           VARCHAR2(8 BYTE),
  REMARK             VARCHAR2(100 BYTE),
  DEL_IF             NUMBER(10),
  CRT_BY             VARCHAR2(10 BYTE),
  CRT_DT             DATE,
  MOD_BY             VARCHAR2(10 BYTE),
  MOD_DT             DATE,
  PLACE_CODE         VARCHAR2(10 BYTE)
)
NOLOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EOBIZORG_PK ON TCO_EOBIZORG
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EOBIZORG_IDX01 ON TCO_EOBIZORG
(BIZORG_NAME, TCO_EOBIZPLACE_PK, END_DATE, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EOBIZPLACE_IDX01 ON TCO_EOBIZPLACE
(LOC_ID, TCO_EOCOMPANY_PK, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EOBIZPLACE_PK ON TCO_EOBIZPLACE
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EOCOMPANY_PK ON TCO_EOCOMPANY
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EOCOMPANY_IDX01 ON TCO_EOCOMPANY
(COM_ID, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPT_IDX01 ON TCO_EODEPT
(DEPT_ID, END_DATE, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPT_PK ON TCO_EODEPT
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPTAPPOINT_PK ON TCO_EODEPTAPPOINT
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPTAPPOINT_IDX01 ON TCO_EODEPTAPPOINT
(APPOINT_DATE, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPTAPPOINTD_PK ON TCO_EODEPTAPPOINTD
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPTAPPOINTD_IDX01 ON TCO_EODEPTAPPOINTD
(TCO_EODEPTAPPOINT_PK, DEPT_ID, DEL_IF)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPTHIS_PK ON TCO_EODEPTHIS
(PK)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TCO_EODEPTHIS_IDX01 ON TCO_EODEPTHIS
(TCO_EODEPAPPOINT_PK, TCO_EODEPT_PK, DEL_IF)
LOGGING
NOPARALLEL;


CREATE PUBLIC SYNONYM TCO_EODEPT FOR TCO_EODEPT;


CREATE PUBLIC SYNONYM TCO_EOBIZORG FOR TCO_EOBIZORG;


CREATE PUBLIC SYNONYM TCO_EOBIZPLACE FOR TCO_EOBIZPLACE;


CREATE PUBLIC SYNONYM TCO_EOCOMPANY FOR TCO_EOCOMPANY;


CREATE PUBLIC SYNONYM TCO_EODEPTAPPOINT FOR TCO_EODEPTAPPOINT;


CREATE PUBLIC SYNONYM TCO_EODEPTAPPOINTD FOR TCO_EODEPTAPPOINTD;


CREATE PUBLIC SYNONYM TCO_EODEPTHIS FOR TCO_EODEPTHIS;


CREATE PUBLIC SYNONYM TCO_EODEPT_TMP FOR TCO_EODEPT_TMP;


ALTER TABLE TCO_EOBIZORG ADD (
  CONSTRAINT TCO_EOBIZORG_PK PRIMARY KEY (PK));


ALTER TABLE TCO_EOBIZPLACE ADD (
  CONSTRAINT TCO_EOBIZPLACE_PK PRIMARY KEY (PK));


ALTER TABLE TCO_EOCOMPANY ADD (
  CONSTRAINT TCO_EOCOMPANY_PK PRIMARY KEY (PK));


ALTER TABLE TCO_EODEPT ADD (
  CONSTRAINT TCO_EODEPT_PK PRIMARY KEY (PK));


ALTER TABLE TCO_EODEPTAPPOINT ADD (
  CONSTRAINT TCO_EODEPTAPPOINT_PK PRIMARY KEY (PK));


ALTER TABLE TCO_EODEPTAPPOINTD ADD (
  CONSTRAINT TCO_EODEPTAPPOINTD_PK PRIMARY KEY (PK));


ALTER TABLE TCO_EODEPTHIS ADD (
  CONSTRAINT TCO_EODEPTHIS_PK PRIMARY KEY (PK));


GRANT SELECT ON  TCO_EODEPT_TMP TO PUBLIC;

GRANT SELECT ON  TCO_EODEPTHIS TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  TCO_EODEPTHIS TO HR;

GRANT SELECT ON  TCO_EODEPTAPPOINTD TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  TCO_EODEPTAPPOINTD TO HR;

GRANT SELECT ON  TCO_EODEPTAPPOINT TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  TCO_EODEPTAPPOINT TO HR;

GRANT SELECT ON  TCO_EODEPT TO PUBLIC;

GRANT SELECT ON  TCO_EOCOMPANY TO PUBLIC;

GRANT SELECT ON  TCO_EOBIZPLACE TO PUBLIC;

GRANT SELECT ON  TCO_EOBIZORG TO PUBLIC;


