INSERT INTO TCO_EOBIZORG ( PK, TCO_EOBIZPLACE_PK, BIZORG_NAME, TCO_EODEPT_PK, SALEORG_YN, PURORG_YN,
REMARK, USE_YN, ST_DATE, END_DATE, DEL_IF, CRT_DT, CRT_BY, MOD_DT, MOD_BY ) VALUES ( 
1, 1, 'SALES', 10, 'Y', 'N', 'CONVERSION', 'Y', '20040101', NULL, 0,  TO_Date( '01/20/2004 01:23:04 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'GEN',  TO_Date( '01/20/2004 02:08:23 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'GEN'); 
INSERT INTO TCO_EOBIZORG ( PK, TCO_EOBIZPLACE_PK, BIZORG_NAME, TCO_EODEPT_PK, SALEORG_YN, PURORG_YN,
REMARK, USE_YN, ST_DATE, END_DATE, DEL_IF, CRT_DT, CRT_BY, MOD_DT, MOD_BY ) VALUES ( 
2, 1, 'PURCHASING', 12, 'N', 'Y', 'CONVERSION', 'Y', '20040101', NULL, 0,  TO_Date( '01/20/2004 01:23:19 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'GEN',  TO_Date( '01/20/2004 04:10:08 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'GEN'); 
INSERT INTO TCO_EOBIZORG ( PK, TCO_EOBIZPLACE_PK, BIZORG_NAME, TCO_EODEPT_PK, SALEORG_YN, PURORG_YN,
REMARK, USE_YN, ST_DATE, END_DATE, DEL_IF, CRT_DT, CRT_BY, MOD_DT, MOD_BY ) VALUES ( 
4, 1, 'PRODUCTION CONTROL', 11, 'N', 'Y', 'manually added', 'Y', '20050106', NULL
, 0,  TO_Date( '01/06/2005 03:44:56 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'thai', NULL, NULL); 
INSERT INTO TCO_EOBIZORG ( PK, TCO_EOBIZPLACE_PK, BIZORG_NAME, TCO_EODEPT_PK, SALEORG_YN, PURORG_YN,
REMARK, USE_YN, ST_DATE, END_DATE, DEL_IF, CRT_DT, CRT_BY, MOD_DT, MOD_BY ) VALUES ( 
5, 1, 'DEPT NOT YET ADDED TO BIZORG', -1, NULL, NULL, NULL, 'Y', '20050106', NULL
, 0,  TO_Date( '01/06/2005 03:48:07 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'thai', NULL, NULL); 
commit;
 
INSERT INTO TCO_EOBIZPLACE ( PK, TCO_EOCOMPANY_PK, TCO_DCCUST_PK, LOC_ID, LOC_NM, LOC_LNM, LOC_FNM,
NATION, REG_NO, TAX_CD, TAX_OFFICE, REPRESENTATIVE, ZIP_CODE, ADDR_NM1, ADDR_LNM1, ADDR_NM2,
ADDR_LNM2, ADDR_NM3, ADDR_LNM3, PHONE_NO, FAX_NO, BIZ_TYPE, BIZ_ITEM, BIZ_GRP, REMARK, USE_YN,
ST_DATE, END_DATE, DEL_IF, CRT_DT, CRT_BY, MOD_DT, MOD_BY ) VALUES ( 
4, 1, NULL, '02', 'BINHDUONG', 'BINHDUONG', 'BINHDUONG', 'VIE', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y'
, '20060512', NULL, 0,  TO_Date( '05/12/2006 02:35:52 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'duc', NULL, NULL); 
commit;
 
INSERT INTO TCO_EOCOMPANY ( PK, COM_ID, COM_NM, NATION, LOC_NATION, FOR_NATION, COM_LNM, COM_FNM,
P_PK, COM_GRP, ACNT_MMDATE, AC_GRP, CORP_NO, PRSN_NAME, RES_NO, BIZ_TYPE, BIZ_ITEM, BIZ_GRP,
ZIP_CODE, ADDR_NM1, ADDR_LNM1, ADDR_NM2, ADDR_LNM2, ADDR_NM3, ADDR_LNM3, PHONE_NO, FAX_NO, URL_ADDR,
USE_YN, ST_DATE, END_DATE, DEL_IF, CRT_DT, CRT_BY, MOD_DT, MOD_BY, SERIAL_NO, TAX_CODE ) VALUES ( 
1, '01', 'SHINWOO', 'VIE', 'VIE', 'KOR', 'SHINWOO', 'SHINWOO', 1, NULL, NULL, NULL
, NULL, ' ', NULL, '1', 'GOLF BAG', NULL, '0650', ' ', ' ', ' ', ' ', ' ', ' ', ' '
, ' ', NULL, 'Y', '20000217', NULL, 0,  TO_Date( '12/05/2003 02:03:06 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'GENUWIN',  TO_Date( '03/02/2007 11:47:30 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thai'
, '123456789', ' '); 
commit;
 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
315, '01', '06', 'Completion', 'Completion', 'Completion', 0, 4, 1, NULL, '20070410'
, NULL, NULL, 0, NULL,  TO_Date( '04/25/2007 04:18:53 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
316, '02', '02', 'HR & Admin', 'HR & Admin', 'HR & Admin', 0, 4, 1, NULL, '20070609'
, NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:33:17 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
317, '03', '03', 'Main Office', 'Main Office', 'Main Office', 0, 4, 1, NULL, '20070608'
, NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:34:08 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'shinwoo',  TO_Date( '09/21/2019 01:52:46 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
318, '04', '04', 'Maintenance', 'Maintenance', 'Maintenance', 0, 4, 1, NULL, '20070609'
, NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
319, '05', '05', 'Newcomers', 'Newcomers', 'Newcomers', 0, 4, 1, NULL, '20070609'
, NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:35:58 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
320, '06', '06', 'Production', 'Production', 'Production', 0, 4, 1, NULL, '20070609'
, NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:36:56 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
321, '07', '07', 'Quality management', 'Quality management', 'Quality management'
, 0, 4, 1, NULL, '20070609', NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:37:25 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
322, '08', '08', 'Sewing', 'Sewing', 'Sewing', 0, 4, 1, NULL, '20070609', NULL, NULL
, 0, NULL,  TO_Date( '06/09/2007 02:37:52 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
323, '09', '09', 'Warehouse', 'Warehouse', 'Warehouse', 0, 4, 1, NULL, '20070609'
, NULL, NULL, 0, NULL,  TO_Date( '06/09/2007 02:38:37 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE, STT ) VALUES ( 
334, '10', '06', 'PURCHASE', 'PURCHASE', 'PURCHASE', 0, 4, 1, NULL, '20090703', NULL
, NULL, 334, 'shinwoo',  TO_Date( '07/03/2009 09:00:38 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'shinwoo',  TO_Date( '07/03/2009 09:23:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL); 
commit;
 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
1, '1000', '06', 'General Director', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'General Director'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
2, '1001', '06', 'Management Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Management Division', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
3, '1002', '06', 'Production Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Production Division', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
4, '1003', '06', 'Quality Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Quality Division'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
5, '1004', '06', 'R & D Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'R & D Division'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
6, '1005', '06', 'Marketing Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Marketing Division', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
7, '1006', '06', 'HR - Admin', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'HR & Admin'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
8, '1007', '06', 'Accounting', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Accounting'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
9, '1008', '06', 'Export - Import', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Export - Import'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
10, '1009', '06', 'Sales', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Sales', 0
, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
11, '1010', '06', 'Production Control', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Production Control', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
12, '1011', '06', 'Purchasing', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Purchasing'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
13, '1012', '06', 'Injection Procurement', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Injection Procurement', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
14, '1013', '06', 'Quality Assurance', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Quality Assurance', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
15, '1014', '06', 'Quality Control ', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Quality Control ', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
16, '1015', '06', 'IQC ', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'IQC ', 0, 'GENUWIN'
,  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
17, '1016', '06', 'OQC', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'OQC', 0, 'GENUWIN'
,  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
18, '1017', '06', 'Production Supervising', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Production Supervising', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
19, '1018', '06', 'Technician', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Technician'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
20, '1019', '06', 'Maintenance', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Maintenance'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
21, '1020', '06', 'Micro System (MS1)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro System (MS1)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
22, '1021', '06', 'Micro Speaker (M10)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M10)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
23, '1022', '06', 'Micro Speaker (M20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
24, '1023', '06', 'Micro Speaker (M30)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M30)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
25, '1024', '06', 'Micro Speaker (M40)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M40)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
26, '1025', '06', 'Micro Speaker (M50)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M50)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
27, '1026', '06', 'Micro Speaker (M60)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M60)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
28, '1027', '06', 'Micro Speaker (M70)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M70)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
29, '1028', '06', 'Diaphragm Ass''y (SA1)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA1)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
30, '1029', '06', 'Diaphragm Ass''y (SA2)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA2)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
31, '1030', '06', 'Diaphragm Ass''y (SA3)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA3)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
32, '1031', '06', 'Diaphragm Ass''y (SA4)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA4)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
33, '1032', '06', 'Diaphragm Ass''y (SA5)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA5)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
34, '1033', '06', 'Diaphragm Ass''y (SA6)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA6)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
35, '1034', '06', 'Voice Coil (V20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Voice Coil (V20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
36, '1035', '06', 'Voice Coil (V30)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Voice Coil (V30)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
37, '1036', '06', 'Voice Coil (V40)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Voice Coil (V40)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
38, '1037', '06', 'Speaker System (S10)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Speaker System (S10)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
39, '1038', '06', 'Speaker System (S20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Speaker System (S20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
40, '1039', '06', 'Speaker System (S30)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Speaker System (S30)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
41, '1040', '06', 'General Speaker (G1A)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G1A)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
42, '1041', '06', 'General Speaker (G2A)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G2A)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
43, '1042', '06', 'General Speaker A1', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker A1', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
44, '1043', '06', 'General Speaker (G1B)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G1B)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
45, '1044', '06', 'General Speaker (G2B)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G2B)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
46, '1045', '06', 'General Speaker (G3A)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G3A)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
47, '1046', '06', 'General Speaker (G3B)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G3B)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
48, '1047', '06', 'Assistant Line (J20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Assistant Line (J20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
49, '1048', '06', 'Assistant Line (J40)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Assistant Line (J40)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
50, '1049', '06', 'Assistant Line (J50)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Assistant Line (J50)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
51, '1050', '06', 'Wooden System (B100)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Wooden System (B100)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
52, '1051', '06', 'Wooden System (B200)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Wooden System (B200)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
53, '1052', '06', 'Wood Working', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Wood Working'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
54, '1053', '06', 'Painting', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Painting'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
55, '1054', '06', 'Mold Injection', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Mold Injection'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
56, '1055', '06', 'Cone Paper (   )', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Cone Paper (   )', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
57, '1056', '06', 'Double Check Line', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Double Check Line', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
58, '1057', '06', 'Warehouse', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Warehouse'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
61, '1058', '06', 'Diaphragm Assy (SA7)', NULL, NULL, 0, 2, 1, NULL, '20031230', NULL
, 'Diaphragm Assy (SA7)', 0, 'GENUWIN',  TO_Date( '12/30/2003 10:49:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
62, '1059', '06', 'Diaphragm Assy (SA8)', NULL, NULL, 0, 2, 1, NULL, '20031230', NULL
, 'Diaphragm Assy (SA8)', 0, 'GENUWIN',  TO_Date( '12/30/2003 10:49:39 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
63, '1060', '06', 'Micro System (MS2)', NULL, NULL, 0, 2, 1, NULL, '20031230', NULL
, 'Micro System (MS2)', 0, 'GENUWIN',  TO_Date( '12/30/2003 12:37:34 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
64, '1061', '06', 'Assistant Line (J30)', NULL, NULL, 0, 2, 1, NULL, '20040213', NULL
, 'Assistant Line (J30)', 0, 'GENUWIN',  TO_Date( '02/13/2004 05:47:45 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
65, '1062', '06', 'Wooden System (B300)', NULL, NULL, 0, 2, 1, NULL, '20040213', NULL
, 'Wooden System (B300)', 0, 'GENUWIN',  TO_Date( '02/27/2004 03:59:06 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
85, '1063', '06', 'DOME Speaker D1B', NULL, NULL, 0, 2, 1, NULL, '20040520', NULL
, 'DOME Speaker D1B', 0, 'GENUWIN',  TO_Date( '05/21/2004 03:54:18 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
86, '1064', '06', 'DOME Speaker D1A', NULL, NULL, 0, 2, 1, NULL, '20040520', NULL
, 'DOME Speaker D1A', 0, 'GENUWIN',  TO_Date( '05/21/2004 03:54:38 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
106, '1065', '06', 'Canteen', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Canteen'
, 0, 'byjoo',  TO_Date( '06/15/2004 02:56:37 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
107, '1066', '06', 'Gardener', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Gardener'
, 0, 'byjoo',  TO_Date( '06/15/2004 02:58:24 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'byjoo'
,  TO_Date( '06/15/2004 03:01:50 PM', 'MM/DD/YYYY HH:MI:SS AM'), '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
108, '1067', '06', 'Cleaner', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Cleaner'
, 0, 'byjoo',  TO_Date( '06/15/2004 02:59:49 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
109, '1068', '06', 'Driver', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Driver'
, 0, 'byjoo',  TO_Date( '06/15/2004 03:01:11 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
110, '1069', '06', 'IT', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'IT', 0, 'byjoo'
,  TO_Date( '06/15/2004 03:03:05 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
111, '1070', '06', 'INNOVATION Team', NULL, NULL, 0, 2, 1, NULL, '20040501', NULL
, 'INNOVATION Team', 0, 'byjoo',  TO_Date( '06/15/2004 03:46:37 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pkanh',  TO_Date( '08/03/2004 04:13:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
125, '1071', '06', 'Wooden System (B400)', NULL, NULL, 0, 2, 1, NULL, '20040625', NULL
, 'Wooden System (B400)', 0, 'byjoo',  TO_Date( '06/25/2004 11:36:54 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1215'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
146, '1072', '06', 'TASK TEAM', NULL, NULL, 0, 2, 1, NULL, '20040801', NULL, NULL
, 146, 'pkanh',  TO_Date( '08/02/2004 01:05:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'pkanh'
,  TO_Date( '08/03/2004 03:52:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
165, '1072', '06', 'TASK TEAM', NULL, NULL, 0, 2, 1, NULL, '20040801', '20041231'
, 'TASK TEAM', 0, 'pkanh',  TO_Date( '08/03/2004 04:14:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
104, 'TEST', '04', 'TEST', NULL, NULL, 0, 2, 1, NULL, '20041115', NULL, NULL, 0, 'tuyen'
,  TO_Date( '11/15/2004 02:15:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
105, 'TEST2', '04', 'TEST2', NULL, NULL, 0, 2, 1, NULL, '20041115', NULL, NULL, 105
, 'tuyen',  TO_Date( '11/15/2004 02:17:09 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa',  TO_Date( '06/01/2005 09:03:14 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
166, 'TEST1.1', '04', 'TEST CHILD', NULL, NULL, 104, 2, 1, NULL, '20050419', NULL
, 'HIEP TEST', 0, 'hiep',  TO_Date( '04/19/2005 09:36:34 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
167, 'TEST 1.2', '04', 'TEST CHILD 2', NULL, NULL, 104, 2, 1, NULL, '20050419', NULL
, NULL, 0, 'hiep',  TO_Date( '04/19/2005 09:37:49 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
187, 'ACC', '04', 'ACCOUNTING', 'ACCOUNTING', 'ACCOUNTING', NULL, 1, 1, NULL, '20050407'
, NULL, NULL, 0, 'thai',  TO_Date( '04/26/2005 07:48:44 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
188, 'AA', '06', 'AA', NULL, NULL, 1, 2, 1, NULL, '20050426', NULL, NULL, 0, 'duc'
,  TO_Date( '04/26/2005 08:04:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
194, 'AAA', '06', 'AAAA', NULL, NULL, 0, 1, 1, NULL, '20050426', NULL, NULL, 0, 'duc'
,  TO_Date( '04/26/2005 08:50:43 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
206, 'TEST1', '04', 'TEST1', NULL, NULL, 0, 2, 1, NULL, '20050512', NULL, NULL, 206
, 'thoa',  TO_Date( '05/12/2005 10:44:29 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa',  TO_Date( '06/01/2005 09:03:24 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
207, 'TEST1.3', '04', 'TEST1.3', NULL, NULL, 0, 2, 1, NULL, '20050512', NULL, NULL
, 207, 'thoa',  TO_Date( '05/12/2005 10:47:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa'
,  TO_Date( '05/12/2005 10:48:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
208, 'TEST1.3', '04', 'TEST1.3', NULL, NULL, 104, 2, 1, NULL, '20050512', NULL, NULL
, 208, 'thoa',  TO_Date( '05/12/2005 10:49:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa'
,  TO_Date( '06/01/2005 09:03:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
0, '0001', '00', 'ESTEC', NULL, NULL, NULL, 2, 1, NULL, '20050513', NULL, NULL, 0
, NULL,  TO_Date( '05/13/2005 02:01:00 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
226, 'TESTING', '11', 'TESTING', NULL, NULL, 0, 1, 1, NULL, '20050601', NULL, NULL
, 0, 'thoa',  TO_Date( '06/01/2005 09:08:14 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
227, 'BB', '06', 'BB', NULL, NULL, 1, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:54:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
228, '2000', '06', 'A', NULL, NULL, 0, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:55:15 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
229, '2001', '06', 'B', NULL, NULL, 228, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:55:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
230, '2002', '06', 'C', NULL, NULL, 229, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:56:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
231, '2003', '06', 'D', NULL, NULL, 229, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:57:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
232, 'ABC', '06', 'ABC', NULL, NULL, 167, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:57:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
1, '1000', '06', 'General Director', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'General Director'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
2, '1001', '06', 'Management Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Management Division', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
3, '1002', '06', 'Production Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Production Division', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
4, '1003', '06', 'Quality Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Quality Division'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
5, '1004', '06', 'R & D Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'R & D Division'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
6, '1005', '06', 'Marketing Division', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Marketing Division', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
7, '1006', '06', 'HR - Admin', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'HR & Admin'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
8, '1007', '06', 'Accounting', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Accounting'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
9, '1008', '06', 'Export - Import', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Export - Import'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
10, '1009', '06', 'Sales', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Sales', 0
, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
11, '1010', '06', 'Production Control', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Production Control', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
12, '1011', '06', 'Purchasing', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Purchasing'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
13, '1012', '06', 'Injection Procurement', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Injection Procurement', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
14, '1013', '06', 'Quality Assurance', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Quality Assurance', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
15, '1014', '06', 'Quality Control ', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Quality Control ', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
16, '1015', '06', 'IQC ', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'IQC ', 0, 'GENUWIN'
,  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
17, '1016', '06', 'OQC', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'OQC', 0, 'GENUWIN'
,  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
18, '1017', '06', 'Production Supervising', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Production Supervising', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
19, '1018', '06', 'Technician', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Technician'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1110'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
20, '1019', '06', 'Maintenance', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Maintenance'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
21, '1020', '06', 'Micro System (MS1)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro System (MS1)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
22, '1021', '06', 'Micro Speaker (M10)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M10)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
23, '1022', '06', 'Micro Speaker (M20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
24, '1023', '06', 'Micro Speaker (M30)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M30)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
25, '1024', '06', 'Micro Speaker (M40)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M40)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
26, '1025', '06', 'Micro Speaker (M50)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M50)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
27, '1026', '06', 'Micro Speaker (M60)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M60)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
28, '1027', '06', 'Micro Speaker (M70)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Micro Speaker (M70)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
29, '1028', '06', 'Diaphragm Ass''y (SA1)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA1)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
30, '1029', '06', 'Diaphragm Ass''y (SA2)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA2)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
31, '1030', '06', 'Diaphragm Ass''y (SA3)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA3)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
32, '1031', '06', 'Diaphragm Ass''y (SA4)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA4)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
33, '1032', '06', 'Diaphragm Ass''y (SA5)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA5)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
34, '1033', '06', 'Diaphragm Ass''y (SA6)', NULL, NULL, 0, 2, 1, NULL, '20031205'
, NULL, 'Diaphragm Ass''y (SA6)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
35, '1034', '06', 'Voice Coil (V20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Voice Coil (V20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
36, '1035', '06', 'Voice Coil (V30)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Voice Coil (V30)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
37, '1036', '06', 'Voice Coil (V40)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Voice Coil (V40)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
38, '1037', '06', 'Speaker System (S10)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Speaker System (S10)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
39, '1038', '06', 'Speaker System (S20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Speaker System (S20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
40, '1039', '06', 'Speaker System (S30)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Speaker System (S30)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
41, '1040', '06', 'General Speaker (G1A)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G1A)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
42, '1041', '06', 'General Speaker (G2A)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G2A)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
43, '1042', '06', 'General Speaker A1', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker A1', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
44, '1043', '06', 'General Speaker (G1B)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G1B)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
45, '1044', '06', 'General Speaker (G2B)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G2B)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
46, '1045', '06', 'General Speaker (G3A)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G3A)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
47, '1046', '06', 'General Speaker (G3B)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'General Speaker (G3B)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
48, '1047', '06', 'Assistant Line (J20)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Assistant Line (J20)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
49, '1048', '06', 'Assistant Line (J40)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Assistant Line (J40)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
50, '1049', '06', 'Assistant Line (J50)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Assistant Line (J50)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
51, '1050', '06', 'Wooden System (B100)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Wooden System (B100)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
52, '1051', '06', 'Wooden System (B200)', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Wooden System (B200)', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
53, '1052', '06', 'Wood Working', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Wood Working'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
54, '1053', '06', 'Painting', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Painting'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
55, '1054', '06', 'Mold Injection', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Mold Injection'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
56, '1055', '06', 'Cone Paper (   )', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Cone Paper (   )', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
57, '1056', '06', 'Double Check Line', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL
, 'Double Check Line', 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
58, '1057', '06', 'Warehouse', NULL, NULL, 0, 2, 1, NULL, '20031205', NULL, 'Warehouse'
, 0, 'GENUWIN',  TO_Date( '12/05/2003 03:20:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
61, '1058', '06', 'Diaphragm Assy (SA7)', NULL, NULL, 0, 2, 1, NULL, '20031230', NULL
, 'Diaphragm Assy (SA7)', 0, 'GENUWIN',  TO_Date( '12/30/2003 10:49:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
62, '1059', '06', 'Diaphragm Assy (SA8)', NULL, NULL, 0, 2, 1, NULL, '20031230', NULL
, 'Diaphragm Assy (SA8)', 0, 'GENUWIN',  TO_Date( '12/30/2003 10:49:39 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
63, '1060', '06', 'Micro System (MS2)', NULL, NULL, 0, 2, 1, NULL, '20031230', NULL
, 'Micro System (MS2)', 0, 'GENUWIN',  TO_Date( '12/30/2003 12:37:34 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1121'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
64, '1061', '06', 'Assistant Line (J30)', NULL, NULL, 0, 2, 1, NULL, '20040213', NULL
, 'Assistant Line (J30)', 0, 'GENUWIN',  TO_Date( '02/13/2004 05:47:45 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
65, '1062', '06', 'Wooden System (B300)', NULL, NULL, 0, 2, 1, NULL, '20040213', NULL
, 'Wooden System (B300)', 0, 'GENUWIN',  TO_Date( '02/27/2004 03:59:06 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1211'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
85, '1063', '06', 'DOME Speaker D1B', NULL, NULL, 0, 2, 1, NULL, '20040520', NULL
, 'DOME Speaker D1B', 0, 'GENUWIN',  TO_Date( '05/21/2004 03:54:18 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
86, '1064', '06', 'DOME Speaker D1A', NULL, NULL, 0, 2, 1, NULL, '20040520', NULL
, 'DOME Speaker D1A', 0, 'GENUWIN',  TO_Date( '05/21/2004 03:54:38 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1111'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
106, '1065', '06', 'Canteen', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Canteen'
, 0, 'byjoo',  TO_Date( '06/15/2004 02:56:37 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
107, '1066', '06', 'Gardener', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Gardener'
, 0, 'byjoo',  TO_Date( '06/15/2004 02:58:24 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'byjoo'
,  TO_Date( '06/15/2004 03:01:50 PM', 'MM/DD/YYYY HH:MI:SS AM'), '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
108, '1067', '06', 'Cleaner', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Cleaner'
, 0, 'byjoo',  TO_Date( '06/15/2004 02:59:49 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
109, '1068', '06', 'Driver', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'Driver'
, 0, 'byjoo',  TO_Date( '06/15/2004 03:01:11 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
110, '1069', '06', 'IT', NULL, NULL, 0, 2, 1, NULL, '20040615', NULL, 'IT', 0, 'byjoo'
,  TO_Date( '06/15/2004 03:03:05 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
111, '1070', '06', 'INNOVATION Team', NULL, NULL, 0, 2, 1, NULL, '20040501', NULL
, 'INNOVATION Team', 0, 'byjoo',  TO_Date( '06/15/2004 03:46:37 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'pkanh',  TO_Date( '08/03/2004 04:13:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
125, '1071', '06', 'Wooden System (B400)', NULL, NULL, 0, 2, 1, NULL, '20040625', NULL
, 'Wooden System (B400)', 0, 'byjoo',  TO_Date( '06/25/2004 11:36:54 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1215'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
146, '1072', '06', 'TASK TEAM', NULL, NULL, 0, 2, 1, NULL, '20040801', NULL, NULL
, 146, 'pkanh',  TO_Date( '08/02/2004 01:05:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'pkanh'
,  TO_Date( '08/03/2004 03:52:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
165, '1072', '06', 'TASK TEAM', NULL, NULL, 0, 2, 1, NULL, '20040801', '20041231'
, 'TASK TEAM', 0, 'pkanh',  TO_Date( '08/03/2004 04:14:41 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
104, 'TEST', '04', 'TEST', NULL, NULL, 0, 2, 1, NULL, '20041115', NULL, NULL, 0, 'tuyen'
,  TO_Date( '11/15/2004 02:15:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
105, 'TEST2', '04', 'TEST2', NULL, NULL, 0, 2, 1, NULL, '20041115', NULL, NULL, 105
, 'tuyen',  TO_Date( '11/15/2004 02:17:09 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa',  TO_Date( '06/01/2005 09:03:14 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
166, 'TEST1.1', '04', 'TEST CHILD', NULL, NULL, 104, 2, 1, NULL, '20050419', NULL
, 'HIEP TEST', 0, 'hiep',  TO_Date( '04/19/2005 09:36:34 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
167, 'TEST 1.2', '04', 'TEST CHILD 2', NULL, NULL, 104, 2, 1, NULL, '20050419', NULL
, NULL, 0, 'hiep',  TO_Date( '04/19/2005 09:37:49 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL
, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
187, 'ACC', '04', 'ACCOUNTING', 'ACCOUNTING', 'ACCOUNTING', NULL, 1, 1, NULL, '20050407'
, NULL, NULL, 0, 'thai',  TO_Date( '04/26/2005 07:48:44 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
188, 'AA', '06', 'AA', NULL, NULL, 1, 2, 1, NULL, '20050426', NULL, NULL, 0, 'duc'
,  TO_Date( '04/26/2005 08:04:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
194, 'AAA', '06', 'AAAA', NULL, NULL, 0, 1, 1, NULL, '20050426', NULL, NULL, 0, 'duc'
,  TO_Date( '04/26/2005 08:50:43 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
206, 'TEST1', '04', 'TEST1', NULL, NULL, 0, 2, 1, NULL, '20050512', NULL, NULL, 206
, 'thoa',  TO_Date( '05/12/2005 10:44:29 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa',  TO_Date( '06/01/2005 09:03:24 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
207, 'TEST1.3', '04', 'TEST1.3', NULL, NULL, 0, 2, 1, NULL, '20050512', NULL, NULL
, 207, 'thoa',  TO_Date( '05/12/2005 10:47:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa'
,  TO_Date( '05/12/2005 10:48:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
208, 'TEST1.3', '04', 'TEST1.3', NULL, NULL, 104, 2, 1, NULL, '20050512', NULL, NULL
, 208, 'thoa',  TO_Date( '05/12/2005 10:49:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'thoa'
,  TO_Date( '06/01/2005 09:03:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
0, '0001', '00', 'ESTEC', NULL, NULL, NULL, 2, 1, NULL, '20050513', NULL, NULL, 0
, NULL,  TO_Date( '05/13/2005 02:01:00 PM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, '1120'); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
226, 'TESTING', '11', 'TESTING', NULL, NULL, 0, 1, 1, NULL, '20050601', NULL, NULL
, 0, 'thoa',  TO_Date( '06/01/2005 09:08:14 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL
, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
227, 'BB', '06', 'BB', NULL, NULL, 1, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:54:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
228, '2000', '06', 'A', NULL, NULL, 0, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:55:15 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
229, '2001', '06', 'B', NULL, NULL, 228, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:55:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
230, '2002', '06', 'C', NULL, NULL, 229, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:56:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
231, '2003', '06', 'D', NULL, NULL, 229, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:57:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
INSERT INTO TCO_EODEPT_TMP ( PK, DEPT_ID, DEPT_TYPE, DEPT_NM, DEPT_LNM, DEPT_FNM, P_PK,
TCO_EOBIZPLACE_PK, TCO_EOCOMPANY_PK, TAC_ABBUDGET_PK, ST_DATE, END_DATE, REMARK, DEL_IF, CRT_BY,
CRT_DT, MOD_BY, MOD_DT, PLACE_CODE ) VALUES ( 
232, 'ABC', '06', 'ABC', NULL, NULL, 167, 2, 1, NULL, '20050701', NULL, NULL, 0, 'duc'
,  TO_Date( '07/02/2005 09:57:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL); 
commit;
 
